/** Master earns this % of profit generated by copiers copying their trades. */
export function commissionFromCopierProfit(copierProfit: number, commissionPct: number) {
  if (copierProfit <= 0) return 0;
  const pct = Math.min(50, Math.max(5, commissionPct));
  return Math.round(copierProfit * (pct / 100) * 100) / 100;
}

export const COMMISSION_MODEL = {
  id: "commission_from_copiers",
  label: "Commission from copiers",
  description:
    "When copiers profit from copying your trades, you earn a percentage of their profit. Payouts are transferred on the platform commission cycle.",
  minPct: 5,
  maxPct: 50,
} as const;
